import pandas as pd
import os

def temp():
    print('hello')


# define path variable for folder containing folders of all the raw .csv data
path = r"D:\School\LHL\capstone_project_data\raw_datasets\pcds_data" 

# create a function to read all files within a folder
def read_files(folder_name):
    # create list which will contain all dataframes generated by .csv files within the folder
    data_frames = []
    # create list of file names contained within the folder
    file_names = os.listdir(f"{path}/{folder_name}")
    # iterate through files within each folder
    for file_name in file_names:
        # ignore 'variable' .csv file in each folder
        if file_name == 'variables.csv':
            continue
        # print function status
        print(f'Reading {file_name}')
        # read each .csv to a dataframe
        station_data_df = pd.read_csv(f"{path}/{folder_name}/{file_name}", skiprows=[0], na_values=[' None','None'])
        # add filename as a new column
        station_data_df['filename'] = file_name
        # append dataframe to list
        data_frames.append(station_data_df)
    return data_frames


# create a function to concatenate all of a single folder's dataframes
def concat_folder_dfs(folder_df_list):
    all_folder_dfs = pd.concat(folder_df_list, join='outer', ignore_index=True)
    return all_folder_dfs